CREATE TABLE [COURSES] (
	[COURSE_ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[NAME] NVARCHAR(50),
	[DESCRIPTION] NVARCHAR(50)
);
GO

CREATE TABLE [GROUPS] (
	[GROUP_ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[COURSE_ID] INT,
	[NAME] NVARCHAR(50)
);
GO

CREATE TABLE [STUDENTS] (
	[STUDENT_ID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[GROUP_ID] INT,
	[FIRST_NAME] NVARCHAR(50),
	[LAST_NAME] NVARCHAR(50)
);
GO

CREATE UNIQUE INDEX [IX_COURSES_COURSE_ID] ON [dbo].[COURSES] ([COURSE_ID])
GO

CREATE UNIQUE INDEX [IX_GROUPS_GROUP_ID] ON [dbo].[GROUPS] ([GROUP_ID])
GO

CREATE UNIQUE INDEX [IX_STUDENTS_STUDENT_ID] ON [dbo].[STUDENTS] ([STUDENT_ID])
GO

